variable "name" {
  description = "Name prefix for the database resources."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,30}$", var.name))
    error_message = "name must start with a letter and be 3-31 characters of lowercase letters, digits and hyphens."
  }
}

variable "vpc_id" {
  description = "ID of the VPC the DB security group is created in."
  type        = string
}

variable "subnet_ids" {
  description = "Private DB subnet IDs (at least two AZs) for the DB subnet group."
  type        = list(string)

  validation {
    condition     = length(var.subnet_ids) >= 2
    error_message = "RDS requires a subnet group spanning at least two Availability Zones."
  }
}

variable "allowed_security_group_ids" {
  description = "Security groups allowed to connect on 3306 (the app tier). No CIDR-based access is offered on purpose."
  type        = list(string)

  validation {
    condition     = length(var.allowed_security_group_ids) > 0
    error_message = "Provide at least one security group allowed to reach the database."
  }
}

variable "engine_version" {
  description = "MySQL major.minor engine version."
  type        = string
  default     = "8.4"

  validation {
    condition     = can(regex("^[0-9]+\\.[0-9]+(\\.[0-9]+)?$", var.engine_version))
    error_message = "engine_version must look like '8.4' or '8.4.3'."
  }
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"

  validation {
    condition     = startswith(var.instance_class, "db.")
    error_message = "instance_class must start with 'db.' (e.g. db.t4g.micro)."
  }
}

variable "allocated_storage_gb" {
  description = "Initial storage in GiB."
  type        = number
  default     = 20

  validation {
    condition     = var.allocated_storage_gb >= 20 && var.allocated_storage_gb <= 65536
    error_message = "allocated_storage_gb must be between 20 and 65536."
  }
}

variable "max_allocated_storage_gb" {
  description = "Upper bound for storage autoscaling in GiB. Must be at least allocated_storage_gb."
  type        = number
  default     = 100

  validation {
    condition     = var.max_allocated_storage_gb >= 20 && var.max_allocated_storage_gb >= var.allocated_storage_gb
    error_message = "max_allocated_storage_gb must be at least 20 and not less than allocated_storage_gb."
  }
}

variable "db_name" {
  description = "Name of the initial database. Matches the DB_NAME the app expects."
  type        = string
  default     = "testdb"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,63}$", var.db_name))
    error_message = "db_name must start with a letter and contain only letters, digits and underscores (max 64)."
  }
}

variable "master_username" {
  description = "Master username. The password is generated by RDS into Secrets Manager."
  type        = string
  default     = "appadmin"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,15}$", var.master_username)) && !contains(["admin", "root"], var.master_username)
    error_message = "master_username must start with a letter, be at most 16 characters, and not be a well-known default like 'admin' or 'root'."
  }
}

variable "multi_az" {
  description = "Run a synchronous standby in a second AZ. Roughly doubles instance cost; recommended for prod."
  type        = bool
  default     = false
}

variable "backup_retention_days" {
  description = "Automated backup retention in days (0 disables backups, which also disables point-in-time recovery)."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 0 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 0 and 35."
  }
}

variable "deletion_protection" {
  description = "Block deletion of the instance until this is turned off. Turn on for prod."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. Fine for dev, never for prod."
  type        = bool
  default     = true
}
